server:
  port: 8079

spring:
  datasource:
    url: jdbc:postgresql://db.thecoffeine.com:5432/thecoffeine
    username: coffeine
    password: m@keV1rtu0s0
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: vitaliyacm@gmail.com
    password: vbynkctoblpqkujy
    properties:
      mail:
        mime:
          charset: utf8
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  rabbitmq:
    host: rabbitmq.thecoffeine.com
    port: 5672
    username: virtuoso
    password: virtuoso
