spring:
  datasource:
    url: jdbc:hsqldb:mem:virtuoso
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbcDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
  mail:
    host: localhost
    port: 2525
    protocol: smtp
    username: test
    password: test
