spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/virtuoso
    username: virtuoso
    password: virtuoso
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ENC(u5bF3Z6cFV077VJW3Llthjk8m9Bj7qoxPBCwx7BI6e3mtZuNKFImqE40KD5PTGPE)
    password: ENC(IxjUidRFhuOD9CkGPpb0zi6gwvUr6/+95lF9Roh2UuU=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
