spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/virtuoso
    username: virtuoso
    password: virtuoso
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: user
    password: pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
